# Generated by Django 5.0.7 on 2024-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
